// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gobjmsfzwsudohtrlpaw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdvYmptc2Z6d3N1ZG9odHJscGF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNDI4MzksImV4cCI6MjA3MDgxODgzOX0.5--Q5DGYUNYawfWdFQMzdroUKT8rJvoxJ5fUmXFcgPE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});